# Generated by Django 5.2 on 2025-04-03 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('resim', models.ImageField(upload_to='skinler/')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasa.kasa')),
            ],
        ),
    ]
