# Generated by Django 5.2 on 2025-04-04 02:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0003_case_rarity_remove_skin_kasa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Katılımcı Bekleniyor'), ('STARTING', 'Başlatılıyor'), ('FINISHED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi'), ('ERROR', 'Hata Oluştu')], default='WAITING', max_length=10)),
                ('mode', models.CharField(choices=[('STANDARD', 'Standart'), ('UNDERDOG', 'Underdog'), ('SHARED', 'Ortak')], default='STANDARD', max_length=10)),
                ('max_participants', models.PositiveSmallIntegerField(default=2)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Savaş bittiğinde açılan tüm itemların toplam değeri', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cases', models.ManyToManyField(related_name='battles', to='kasa.case')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_battles', to='kasa.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseBattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_unboxed_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Bu katılımcının açtığı itemların toplam değeri', max_digits=12)),
                ('is_winner', models.BooleanField(default=False, help_text='Bu katılımcı savaşı kazandı mı?')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='kasa.casebattle')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to='kasa.userprofile')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('battle', 'user_profile')},
            },
        ),
        migrations.CreateModel(
            name='CaseBattleUnboxing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unboxed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('battle_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unboxings', to='kasa.casebattleparticipant')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasa.case')),
                ('unboxed_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasa.skin')),
            ],
            options={
                'ordering': ['unboxed_at'],
            },
        ),
    ]
