# Generated by Django 5.2 on 2025-04-04 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0005_alter_case_image_url_alter_casebattle_total_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casebattleparticipant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='casebattle',
            name='num_bots',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casebattleparticipant',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casebattleparticipant',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to='kasa.userprofile'),
        ),
    ]
