# Generated by Django 5.2 on 2025-04-03 15:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0002_skin_nadirlik_kazanilanskin_kullaniciprofili'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color_hex', models.CharField(default='#FFFFFF', help_text='CSS Hex kodu', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Rarities',
            },
        ),
        migrations.RemoveField(
            model_name='skin',
            name='kasa',
        ),
        migrations.RemoveField(
            model_name='kazanilanskin',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='kazanilanskin',
            name='skin',
        ),
        migrations.RemoveField(
            model_name='kullaniciprofili',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='fiyat',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='nadirlik',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='resim',
        ),
        migrations.AddField(
            model_name='skin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skin',
            name='image_url',
            field=models.URLField(blank=True, help_text="Skin görselinin URL'si", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='skin',
            name='name',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Piyasa değeri', max_digits=10),
        ),
        migrations.CreateModel(
            name='CaseSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(help_text='Çıkma olasılığı (örn: 0.05)')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasa.case')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasa.skin')),
            ],
            options={
                'ordering': ['-probability'],
                'unique_together': {('case', 'skin')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='skins',
            field=models.ManyToManyField(related_name='cases', through='kasa.CaseSkin', to='kasa.skin'),
        ),
        migrations.AddField(
            model_name='skin',
            name='rarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skins', to='kasa.rarity'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('trade_url', models.URLField(blank=True, help_text="Steam Takas URL'niz", max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Mevcut'), ('USED_UPGRADE', 'Yükseltildi'), ('WITHDRAWN', 'Çekildi')], default='AVAILABLE', max_length=20)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasa.skin')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='kasa.userprofile')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='UpgradeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('success_chance', models.FloatField()),
                ('rolled_number', models.FloatField(blank=True, null=True)),
                ('was_successful', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_skin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasa.skin')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_attempts', to='kasa.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Kasa',
        ),
        migrations.DeleteModel(
            name='KazanilanSkin',
        ),
        migrations.DeleteModel(
            name='KullaniciProfili',
        ),
    ]
