# Generated by Django 5.2 on 2025-04-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0004_casebattle_casebattleparticipant_casebattleunboxing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casebattle',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='casebattleparticipant',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casebattleparticipant',
            name='total_unboxed_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='skin',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userinventoryitem',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Mevcut'), ('USED_UPGRADE', 'Yükseltildi'), ('WITHDRAWN', 'Çekildi'), ('IN_BATTLE', 'Savaşta')], default='AVAILABLE', max_length=20),
        ),
    ]
