# Generated by Django 5.2 on 2025-04-04 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0006_alter_casebattleparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casebattle',
            name='num_bots',
        ),
    ]
