"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-ai_#9!m%kn@(y6gq!kcfr+j*956e-)nj58#9-b3qz6r##vk6^@'

DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # django-allauth için gerekli

    # Üçüncü Parti Uygulamalar
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # --- BU İKİ SATIRI KONTROL EDİN ---
    'allauth.socialaccount.providers.openid', # <--- BU SATIRI EKLEYİN!
    'allauth.socialaccount.providers.steam',
    # --- --- --- --- --- --- --- --- ---

    # Kendi Uygulamalarımız
       'kasa.apps.KasaConfig',  # Uygulama adını 'kasa' olarak değiştirdiğinizi varsayıyorum
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware", # allauth
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Proje geneli templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ROOT_URLCONF = "config.urls"
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # Admin
    'allauth.account.auth_backends.AuthenticationBackend', # allauth
]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

LANGUAGE_CODE = 'tr-tr'
TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-allauth Ayarları

# --- Eski Ayarları Kaldırın veya Yorum Satırı Yapın ---
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email' # <- KALDIRIN/YORUM YAPIN
# ACCOUNT_EMAIL_REQUIRED = False # <- KALDIRIN/YORUM YAPIN
# ACCOUNT_USERNAME_REQUIRED = False # <- KALDIRIN/YORUM YAPIN

# --- Yeni Ayarlar ---
ACCOUNT_EMAIL_VERIFICATION = 'none' # Eposta doğrulaması kapalı
ACCOUNT_UNIQUE_EMAIL = False      # Emaillerin benzersiz olması GEREKMİYOR (Steam odaklı)
ACCOUNT_LOGIN_METHODS = {'username'} # Sadece admin panel için username ile girişe izin ver (email ile girişi kapatır)
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False # Şifre tekrarı sorma (kayıt kapalı olacağı için önemli değil)
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter' # Varsayılan adaptör
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter' # Varsayılan sosyal adaptör

# Sosyal Hesap Kayıt Ayarları
SOCIALACCOUNT_AUTO_SIGNUP = True        # Steam'den geleni otomatik kaydet
SOCIALACCOUNT_EMAIL_VERIFICATION = ACCOUNT_EMAIL_VERIFICATION # Eposta doğrulamasını ana ayarla aynı yap
SOCIALACCOUNT_EMAIL_REQUIRED = False    # Sosyal hesap için email zorunlu değil
# SOCIALACCOUNT_FORMS = {'signup': 'yourapp.forms.MyCustomSocialSignupForm'} # İsterseniz özel form
# SOCIALACCOUNT_LOGIN_ON_GET=True # Tek tıklamayla sosyal giriş (isteğe bağlı)

# Siteye Doğrudan Kayıt/Giriş Ayarları (Devre Dışı Bırakma)
ACCOUNT_ALLOW_REGISTRATION = False      # Siteye doğrudan yeni kullanıcı kaydını kapat
# ACCOUNT_SIGNUP_FORM_CLASS = None      # Özel kayıt formu kullanma

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_GET = True # Tek tıklama ile çıkış

# --- STEAM PROVIDER AYARLARI (Aynı kalmalı) ---
SOCIALACCOUNT_PROVIDERS = {
    'steam': {
        'APP': {
            'client_id': '0C43BB67683B8E53B8E3028C126C16A3', # DEĞİŞTİRDİĞİNİZDEN EMİN OLUN!
            'secret': '0C43BB67683B8E53B8E3028C126C16A3', # DEĞİŞTİRDİĞİNİZDEN EMİN OLUN!
        },
    }
}
# --- --- --- --- --- --- --- ---